languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Tinkers.space"
#logo = "img/profile.jpg"
description = "Software Engineer, Architect, Cloud lover, Linux Advocate containerize all the things!"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Robert Fletcher"
  image = "img/profile.jpg"
  headline = "Software Engineer, Architect, Cloud lover, Linux Advocate containerize all the things!"
  bio = "Software Engineer, Architect, Cloud lover, Linux Advocate containerize all the things!"
  links = [
    { twitter = "https://twitter.com/robrotheram" },
    { github = "https://github.com/robrotheram" },
  ]
