language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo -t hugo-orbit-theme

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_API_KEY}
    local_dir: public
    skip_cleanup: true
